version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install sphinx sphinx-rtd-theme
      
  pre_build:
    commands:
      - echo "Creating documentation structure..."
      - mkdir -p docs/build/html
      
  build:
    commands:
      - sphinx-build -b html . docs/build/html
      
artifacts:
  files:
    - docs/build/html/**/*
  base-directory: docs/build/html
