version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Setting up Python environment..."
      - python --version
      - pip --version

  pre_build:
    commands:
      - echo "Installing dependencies from requirements.txt..."
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - echo "Verifying installation..."
      - pip list | grep -i sphinx

  build:
    commands:
      - echo "Building HTML documentation with make..."
      - make html
      - echo "Verifying build output..."
      - ls -la _build/html/

  post_build:
    commands:
      - echo "Build completed successfully!"
      - echo "Generated files:"
      - find _build/html -name "*.html" | head -10

artifacts:
  files:
    - '_build/html/**/*'
  base-directory: '_build/html'

cache:
  paths:
    - '/root/.cache/pip/**/*'
