version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Building documentation..."
      - sphinx-build -b html . _build/html
      - echo "Verifying build output..."
      - ls -la _build/html/

artifacts:
  files:
    - '**/*'
  base-directory: '_build/html'

cache:
  paths:
    - '/root/.cache/pip/**/*'
