version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      
  pre_build:
    commands:
      - echo "Starting Sphinx documentation build..."
      - ls -la
      - echo "Checking for conf.py and index.rst:"
      - ls -la *.py *.rst || echo "Files not in root"
      
  build:
    commands:
      - echo "Building HTML documentation..."
      - make html
      
  post_build:
    commands:
      - echo "Build completed successfully"
      - ls -la _build/html/
      
artifacts:
  files:
    - '_build/html/**/*'
  base-directory: '_build/html'
cache:
  paths:
    - '/root/.cache/pip/**/*'
