version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Building documentation..."
      - sphinx-build -b html . _build/html
      - echo "Copying appspec.yml to build output..."
      - cp appspec.yml _build/html/
      - echo "Verifying build output..."
      - ls -la _build/html/
      - echo "Checking for appspec.yml..."
      - ls -la _build/html/appspec.yml
artifacts:
  files:
    - '**/*'
  base-directory: '_build/html'
cache:
  paths:
    - '/root/.cache/pip/**/*'
