version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "=== Checking project structure ==="
      - ls -la
      - echo "=== Checking for Makefile ==="
      - if [ -f "Makefile" ]; then echo "Makefile exists"; cat Makefile; else echo "Makefile not found"; fi
      - echo "=== Checking for conf.py ==="
      - if [ -f "conf.py" ]; then echo "conf.py exists"; else echo "conf.py not found"; fi

  build:
    commands:
      - echo "=== Building documentation with sphinx-build ==="
      - mkdir -p _build/html
      - sphinx-build -b html . _build/html
      - echo "=== Checking build output ==="
      - ls -la _build/html/

  post_build:
    commands:
      - echo "Build completed successfully!"
      - find _build/html -name "*.html" | head -5

artifacts:
  files:
    - '_build/html/**/*'
  base-directory: '_build/html'

cache:
  paths:
    - '/root/.cache/pip/**/*'
